# Site settings
author: Millard
title: MillardxMillard
header-img: img/home-bg.png
email: millardjimmy@gmail.com
copyright_name: Millard
description: > # this means to ignore newlines until "baseurl:"
  A Millard Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  millardjimmy

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
